services:
  postgres:
    image: postgres:17.4-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/src/main/resources/reset-db.sql:/docker-entrypoint-initdb.d/reset-db.sql

  backend:
    build: ./backend
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      WATCHPACK_POLLING: true
      CHOKIDAR_USEPOLLING: true
      VITE_HMR_HOST: localhost
      VITE_HMR_PORT: 3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  pgdata:
