DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS users_roles CASCADE;
DROP TABLE IF EXISTS cnh CASCADE;

ALTER SEQUENCE IF EXISTS users_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS roles_id_seq RESTART WITH 1; 
ALTER SEQUENCE IF EXISTS cnh_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS users_roles_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS cnh_id_seq RESTART WITH 1;